export const LOGIN = "/log-In";
export const SIGNUP = "/sign-Up";
export const HOSTEL = "/hostel";
export const VERIFY_EMAIL = "/verify";
export const CREATECOMMENTS = "/create-comments";
export const READCOMMENTS = "/read-comments";
export const ENTEREMAIL =  "/forgotten-password";
export const NEWPASSWORD= "/forgotten-password/id/verify/token"
export const UPLOADHOSTEL = "/upload-hostel"
export const ADDROOMS = "/add-Rooms"
export const BOOKING = "/hostelRoom/book-room"
export const GETBOOKING = "/hostelRoom/get-bookings"